language: go

sudo: false

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  global:
    - GO111MODULE=on

script:
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - build/ofelia_${TRAVIS_TAG}_darwin_amd64.tar.gz
    - build/ofelia_${TRAVIS_TAG}_linux_amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true
